# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='subject',
        ),
    ]
