# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0002_auto_20190310_2239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventguest',
            unique_together=set([('event', 'guest')]),
        ),
    ]
