# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20190530_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='circle',
            field=models.ManyToManyField(blank=True, null=True, to='agenda.Circle'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
