# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20190530_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='circle',
            field=models.ManyToManyField(blank=True, to='agenda.Circle'),
        ),
    ]
