# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
